### ISSUE TITLE
Define a new output line type for Grid-Stat for distance-map based metrics for binary fields

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#600]
See Eric for details.  But we need to include the Baddeley Delta metric and several others that come output of SptialVx.
<i>[MET-600] created by johnhg</i>

**Comment by dwfncar** [comment]
Met with Eric G. on 1/17/2019 (and again on 6/18/2019) to discuss his DTC visitor project.
<br/>
Distance maps are always based on a threshold.
<br/>
Compute distance map for FCST field and then for OBS field separately.
<br/>
Use 2 distance maps to compute these metrics.
<br/>
<br/>
Also consider the "generalized distance transform"... instead of computing the *shortest* distance from each grid point to a set, calculate the distance from the grid point to EVERY point in set A and take the mean of them.
<br/>

<br/>
Tasks:
<br/>
- Write a function to compute minimum distance map (i.e. min distance from each grid point to an event).
<br/>
- Write a function to compute average distance map (i.e. mean distance from each grid point to all events).
<br/>
- Write the results to a new Grid-Stat line type named "DMAP" (for distance-map based stats).
<br/>
- Like neighborhood statistics, compute the distance maps for the whole domain and then report statistics for each subregion separately (i.e. compute distance map once and then derive stats for each subregion).
<br>
- Use these distance maps to compute distance metrics, as defined by Eric and including...
<br>
- LINE_TYPE(DMAP) TOTAL FY OY FBIAS BADDELEY HAUSDORFF<br>
   MED_FO MED_OF MED_MIN MED_MAX MED_MEAN (here MED = mean error distance)<br>
   FOM_FO FOM_OF FOM_MIN FOM_MAX FOM_MEAN (here FOM = Pratt's figure of merit)<br>
<br/>
  - Baddeley&#39;s Delta Metric
<br>
  - Hausdorff Metric
<br/>
  - Mean Error Distance (MED) of A to B, B to A, min/max/mean of A to B and B to A
<br/>
     - MED_FO, MED_OF, MED_MIN, MED_MAX, MED_MEAN, FOM_FO, FOM_OF
<br/>

User-configurable items...
 - Existing cat_thresh settings are applied here.
 - For MED nothing else is required.
 - For FOM, need an alpha value (not to be confused with significance level).  Perhaps fom_param.
 - For Baddeley, need the baddeley_p (default = 2).
 - For Baddeley, max_dist = NA (default infinite). 

distance_map = {
   baddeley_p = 2; // is an exponent for the lp-norm
   baddeley_max_dist = NA; // in grid units
   fom_alpha = 0.1;
}

Eric confirms that these scores cannot be aggregated in Stat-Analysis.
See Spatial Vx manual here:
https://cran.r-project.org/web/packages/SpatialVx/SpatialVx.pdf

See ICP cases for examples:<br>
https://ral.ucar.edu/projects/icp/<br>

Suggested library function:
DataPlane distance_map();
Could make it a member function of DataPlane class instead of utility function.
fcst_dmap = fcst_dp.distance_map();
obs_dmap = obs_dp.distance_map();

And then we'll need additional functions to derive stats from the these maps.  See the R code referenced below for details.

If there are no events in the forecast *OR* the observation field, report NA for all statistics.

<br/>
Add a new tool implement the SPCT (Spatial Prediction Comparison Test) method.
<br/>
Reads input from two competing forecasts and also reads point or gridded observations.
<br/>
Compute A1 = abs(FCST1 - OBS) and A2 = abs(FCST2 - OBS).
<br/>
Compute A1 - A2.
<br/>
Compute a variaogram from this field and use it to compute some statistics to decide which forecast is better in terms of the average loss differential.  When you have a grid then there&#39;s a fast way of computing a variogram... get that from Eric.
<br/>

<br/>
Add a new tool for image warping on continuous data.  But this would just be for testing, not for general distribution yet.
<br/>
You start with values at each grid point, do image warping, and then end up with values slightly offset from the grid points.  So we need to interpolate the result back to the vx grid.
<br/>
Eric described that we need to do an interactive process to build up the warp.
<br/>
Convert Eric&#39;s R code to C++. 
<i>by johnhg</i>

**Comment by TaraJensen** [comment]
Eric needs to get his part of the DTC visitor project done.  Please split between 2702691 and 2780541 for this project.

**Comment by JohnHalleyGotway** [comment]
On 06/19/2019, I committed many changes to the feature_600_DMAP branch including...
- Add DMAPInfo class to met_stats.h to store distance map stats.
- Add distance_map config file dictionary for Grid-Stat and update grid_stat_conf_info.h/.cc to parse it.
- Enhance Grid-Stat to loop over the categorical thresholds for each field and write DMAP output lines (currently with default 0 or NA values).
- Enhance Grid-Stat to write DMAP fields to the output NetCDF matched pairs file.
- Update the version number from met-8.1 to met-9.0 and add DMAP output line type to the new met-9.0 header table file.
- Test to make sure that stat_analysis can read the DMAP output and run the summary job on it's columns.

**Comment by hsoh-u** [comment]
From Eric:
equations for distance map:

d(x, O) = distance map for observations
d(x, F) = distance map for forecast
w( d(x, A) ) = min( d(x, A), constant ) [I think we're calling constant bdelta_const or something?]
D(F,O) = w( d(x, F) ) - w( d(x, O) )
1_O = binary field for observations
1_F = binary field for forecast
n_O = sum( 1_O )
n_F = sum( 1_F )
N = total number of grid points in the field

MED(F,O) = MED_FO = sum( d(x, F) * 1_O ) / n_O

MED(O,F) = MED_OF = sum( d(x, O) * 1_F ) / n_F

avg MED = 0.5 * ( MED( F, O ) + MED( O, F ) )

min MED = min( MED( F, O ), MED( O, F ) )

max MED = max( MED( F, O ), MED( O, F ) )

Hausdorff = H
H( F, O ) = H( O, F ) = max( abs( D(F, O) ) )

Baddeley's Delta = D
D( F, O ) = D( O, F ) = {(1 / N) * sum( abs( D(F, O) )^p ) }^(1 / p)
[the sum is over the entire domain of D(F, O).]

FOM_FO = ( 1 / max( n_F, n_O ) ) * sum( 1_O / (1 + alpha * d(x,F)^2) )
[i.e., the sum is over only the 1-valued points in the observation field]

FOM_OF = ( 1 / max( n_F, n_O ) ) * sum( 1_F / (1 + alpha * d(x,O)^2) )

avg FOM = 0.5 * ( FOM(F, O) + FOM( O, F ) )

min FOM = min( FOM( F, O ), FOM( O, F ) )

max FOM = max( FOM( F, O ), FOM( O, F ) )

Zhu's measure = Z

Z(F, O) = lambda * sqrt( mean( (1_F - 1_O)^2 ) ) + (1 - lambda) * MED(F, O)

etc. for O, F, avg, min and max

**Comment by JohnHalleyGotway** [comment]
Eric, Howard, and John met on 9/17/2019 to review Howard and Eric's comparisons.  Everything matches except Baddeley Delta metric.  Eric will double-check his computations and tell Howard.

- [x] Eric will send John 1-2 pages of description to be included in the Grid-Stat section of the MET User's Guide:
https://dtcenter.org/sites/default/files/community-code/met/docs/user-guide/MET_Users_Guide_v8.1.1.pdf

- [ ] John will add Eric's docs to the MET User's Guide, add the equations to Appendix C, and add a new output table for the Grid-Stat output section.

- [x] John will update the config/README file with a description of the DMAP configuration options.

- [x] John will enhance an existing unit test to produce this DMAP output.

**Comment by JohnHalleyGotway** [comment]
Howard merged the branch into develop on 9/27/2019.  This updates the MET version number from 8.1 to 9.0.  John updated all of the Grid-Stat config files (in met and test) by adding output_flag.dmap entry, nc_pairs_flag.distance_map, and the distance_map dictionary with options.

**Comment by JohnHalleyGotway** [comment]
Three issues to debug:

(1) Currently the distance map is computed for all grid points, whether they contain valid data values or not.  Should we instead set the distance maps to a bad data value anywhere the raw data contains bad data?

Yes we should.  John updated the distance_map() function in data_plane_util.cc to set the distance map to bad data anywhere the input thresholded field was bad data.  Also, updated the DMapInfo::set() function to count up and report the number of valid data values.

(2) When FY and/or OY = 0 we get "-nan" in the output.  Need to add error checks to catch this and replace with "NA" in the output.
  - For 2m TMP<300, the event occurs most places in CONUS.
  - For 2m TMP>=300, the event occurs in very few places in CONUS.

We compute the distance map over the full model domain and then subset it over the masking region, like LMV.  For TMP<300, the distance map is a constant 0 over LMV, and for TMP>=300, the distance maps contain values between 5 and 28 over LMV.
Updated the met_stats.cc to check for divide by zero and store as bad data.

(3) All the Baddeley distances were resulting in 0.  I found that was because the baddeley max distance is being initialized from the config file to bad data (i.e. -9999).  And the code checking for the max distance wasn't checking for the bad data value.  Updated the logic to handle the bad data value.

**Comment by JohnHalleyGotway** [comment]
Documentation from Eric:
[METtotrialDistanceMeasures.docx](https://github.com/NCAR/MET/files/3678519/METtotrialDistanceMeasures.docx)

**Comment by JohnHalleyGotway** [comment]
All done with this issue.  Howard added the distance map computations to the library code; John updated the Grid-Stat code to call the library code; Howard and Eric carefully tested MET's algorithm with the one in R; John tweaked it to better handle missing data; Eric wrote up the documentation; John added it to the MET User's Guide; John updated the NB reference revision to get past the new addition of DMAP output lines.
