### ISSUE TITLE
Update definition of NCEP Grids

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#893]
MET&#39;s definitions of NCEP grids have become outdated.  The NCEP grids are currently defined in the file find_grid_by_name.h.
<br/>

<br/>
This task is to do the following:
<br/>

<br/>
(1) Rather than defining grids in the compiled code, consider reading them from a data file at runtime.  This is not required... just think about a better solution.
<br/>

<br/>
(2) Refer to grids defined here:
<br/>
   <a href="http://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html">http://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html</a>
<br/>

<br/>
(3) Rather than getting info from that website, consider the following method:
<br/>
 - Run copygb to regrid data to these NCEP grids.
<br/>
 - Use wgrib to dump the grid definitions.
<br/>
 - Write a script to convert those grid definitions the formats used in find_grid_by_name.h.
<br/>

<br/>
(4) Add a new block of grid definitions for gaussian grids.
<br/>

<br/>
See attached script and output file for a starting point.
<i>[MET-893] created by johnhg</i>

**Comment by lisagoodrich** [comment]
Original JIRA attachment location:
https://sdg.rap.ucar.edu/jira/browse/MET-893?filter=12903

Remove .txt once this is downloaded.  github can't save .ksh extensions.
[gen_ncep_grids.ksh.txt](https://github.com/NCAR/MET/files/3292310/gen_ncep_grids.ksh.txt)

[NCEP_GRIDS.txt](https://github.com/NCAR/MET/files/3292312/NCEP_GRIDS.txt)

**Comment by JohnHalleyGotway** [comment]
As discussed on 11/04/2019, be sure to add grids 132, 227, and 148 (but check them all).

**Comment by JohnHalleyGotway** [comment]
Began work on this issue on 02/10/2020.  I updated the gen_ncep_grids.ksh script to run copygb from UPPV4.0.1, figuring it'd have the most recent grid updates.  I found the following:

SKIP 28 UNSUPPORTED GRID DEFINITIONS:
- SKIP G008: Not supported because the range of longitude is 363.104.
- SKIP 18 thinned Lat/Lon grids that are not supported which result in a segfault in MET:
G021, G022, G023, G024, G025, G026, G037, G038, G039, G040, G041, G042, G043, G044, G061, G062, G063, G064
- SKIP 9 Arakawa grids that are not supported in MET:
G083, G093, G094, G095, G096, G097, G099, G190, G192

+++++++++++++++++++++++++++++++++++++++++++++++++++++

ADD 51 NEW GRID DEFINITIONS

- Add 22 Lat/Lon grid definitions:
G010, G011, G012, G013, G014, G015, G016, G017, G018, G150, G161, G174, G176, G180, G181, G182, G183, G235, G238, G239, G244, G253
- Add 11 Polar Stereographic grid definitions:
G091, G092, G151, G160, G171, G172, G179, G189, G198, G219, G220
- Add 11 Lambert Conformal grid deifinitions:
G132, G138, G139, G140, G147, G148, G184, G187, G188, G197, G200
- Add 6 Gaussian grid definitions:
G098, G126, G127, G128, G129, G170
- Add 1 Mercator grid definition:
G194

+++++++++++++++++++++++++++++++++++++++++++++++++++++

NOTES:
The wgrib output for G161 is wrong (latlon: lat  50.750000 to -0.250000 by 0.000000  nxny 13974          long 271.750000 to -19.750000 by 0.000000, (137 x 102) scan 0 mode 72 bdsgrid 1).  Use MET's values instead:
DEBUG 4: Latitude/Longitude Grid Data:
DEBUG 4:      lat_ll: -0.25
DEBUG 4:      lon_ll: 88.25
DEBUG 4:   delta_lat: 0.5
DEBUG 4:   delta_lon: 2.12774
DEBUG 4:        Nlat: 102
DEBUG 4:        Nlon: 137

**Comment by JohnHalleyGotway** [comment]
Added 51 NCEP grids that were missing.  Double-checked these additions by regridding using copygb and regrid_data_plane and then running pcp_combine to check that the grids match.
